Set `USER` env variable only if it is not already set.
facebookresearch/hydra pull request #1060
Opened 2020-10-14 15:19 UTC by shagunsodhani

Fixes #1059.

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes/No

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2020-10-14 17:15 UTC, omry requested changes
can you remove this and see which tests are breaking? we can probably just mock the environment variable on the specific tests.

2020-10-14 19:20 UTC, shagunsodhani commented
Will get to it in a couple of hours.

2020-10-14 21:33 UTC, shagunsodhani commented
ahh I think I should be explicitly unsetting the `USER` env variable if it was not originally set. I was earlier relying on the python context but then I realized that `os.environ` is a global object.

2020-10-15 01:07 UTC, omry requested changes

2020-10-15 01:07 UTC, omry commented on tests/test_examples/test_tutorials_basic.py
> +    should_remove_variable = False
Use monkeypatch.
```python
def test_advanced_ad_hoc_composition(
    minkeypatch: Any, tmpdir: Path, args: List[str], expected: Any
) -> None:
  monkeypatch.setenv("USER", "test_user")
  ...
```

2020-10-15 01:08 UTC, omry commented
Also:
1. Add a news fragment.
2. Cherry pick to the 1.0 branch.

2020-10-15 15:38 UTC, shagunsodhani commented on tests/test_examples/test_tutorials_basic.py
> +    should_remove_variable = False
Ohh sweet :)

2020-10-15 15:47 UTC, shagunsodhani commented
> Also:
> 
> 1. Add a news fragment.
> 2. Cherry pick to the 1.0 branch.

For 1, isnt this an internal change? I mean the end-user doesnt (

2020-10-15 15:48 UTC, shagunsodhani commented
oops sorry - accidentally closed it :)

2020-10-15 16:21 UTC, omry commented
We do, if anything we do not update news in master.
I am planning to eventually release 1.0.4 with some minor patches.

2020-10-15 16:55 UTC, merged