Fix a broken url caused by typo
facebookresearch/hydra pull request #1078
Opened 2020-10-20 02:18 UTC by saintmalik

## Summary

Easy navigation and easy reading 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

(NO)

2020-10-20 16:52 UTC, shagunsodhani approved these changes

2020-10-20 17:31 UTC, omry requested changes
The version you fixed is the next version. can you also fix in the versioned_docs directory for 1.0 ?

2020-10-21 10:59 UTC, shagunsodhani commented
Looks good! Thanks

Note to self: Cherry-pick the changes to 1.0_branch

2020-10-21 21:50 UTC, jieru-hu commented
thx for the fix! @saintmalik

2020-10-22 00:57 UTC, merged