[1.0_branch] Add Optuna sweeper plugin
facebookresearch/hydra pull request #1169
Opened 2020-11-24 11:57 UTC by toshihikoyanase

## Motivation

This PR backports the change in  #1132 to the 1.0 branch. It cherry-picked the commit https://github.com/facebookresearch/hydra/commit/4f1018d7e0575cd394020bb668d1a8a3243fa9aa.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

This PR includes the same tests as  #1132.

## Related Issues and PRs

The original PR is  #1132.

2020-11-26 22:18 UTC, omry commented
I am holding off merging it because a followup would be to make an initial release of the plugin, would you like to take care of it?

2020-11-27 01:53 UTC, toshihikoyanase commented
@omry
I'm interested in the followup. Could you briefly explain it?

2020-11-27 01:57 UTC, omry commented
Sure, have you ever released a pip package?
read about it.

Basically, we should release a package for it. after your initial release add me as a second owner in pypi (user omry).

2020-11-27 02:01 UTC, omry requested changes

2020-11-27 02:01 UTC, omry commented on plugins/hydra_optuna_sweeper/setup.py
> +    version="0.0.1",
Or actually, since we are expecting the change to the config structure:
0.9.0-rc1

2020-11-27 02:02 UTC, merged

2020-11-27 02:04 UTC, omry commented
Okay, merged to the 1.0_branch.
Try to release from there. If you run into difficulties let me know.

2020-11-27 08:34 UTC, toshihikoyanase commented
@omry Thank you for your instruction. I have released Optuna packages, and I think I can release the plugin by myself. I'll make a release from `1.0_branch`.

2020-11-27 08:39 UTC, omry commented
What do you mean, have you released the hydra-optuna-sweeper package to pypi yet? I am not seeing it there.
Don't  forget to make me an owner as well once you do.

2020-11-27 09:58 UTC, toshihikoyanase commented
What I wanted to say was that I have released some other libraries and I know how to release packages at pypi.

Now, I released the hydra-optuna-sweeper package [here](https://pypi.org/project/hydra-optuna-sweeper/) and invited you as an owner. Please check the invitation.

2020-11-27 17:08 UTC, omry commented
Yup, got it. looking good!
Can you send a PR bringing the [plugin page](https://hydra.cc/docs/next/plugins/optuna_sweeper) to section in part with the rest?

2020-11-28 08:50 UTC, toshihikoyanase commented
I'm sorry but I didn't get your point well. Should I add missing badges such as `pypi` and `license` like the other sweepers as follows?

![image](https://user-images.githubusercontent.com/3255979/100497767-e61b2880-31a0-11eb-88fe-9edcd14f7ad2.png)

2020-11-28 09:36 UTC, omry commented
Yup, this is exactly what I mean!
send a PR against master to update it.

2020-11-28 10:24 UTC, toshihikoyanase commented
Thank you for your reply. I submitted #1172, so please take a look!

2020-11-29 21:52 UTC, omry commented
Awesome.