cherry-pick #1312 #1309
facebookresearch/hydra pull request #1330
Opened 2021-01-23 01:15 UTC by jieru-hu

remove Plugins from Singleton get_state (#1312)
fix key pair name - add user (#1309)

2021-01-23 01:30 UTC, omry commented
Are you planning on releasing hydra 1.0.6 for this?
if so, you should include a news fragment.

2021-01-26 23:16 UTC, omry requested changes

2021-01-26 23:16 UTC, omry commented on NEWS.md
> +- Remove `Plugins` from `Singleton.get_state()` ([#1330](https://github.com/facebookresearch/hydra/issues/1330))
This file is generated from the news fragments, do not edit it.

2021-01-26 23:18 UTC, jieru-hu commented
> Are you planning on releasing hydra 1.0.6 for this?
> if so, you should include a news fragment.

ah I see, i checked https://github.com/facebookresearch/hydra/tree/1.0_branch/news before this and didnt see anything under there so I thought 1.0_branch behaves differently. will fix.

2021-01-26 23:23 UTC, jieru-hu commented
> > Are you planning on releasing hydra 1.0.6 for this?
> > if so, you should include a news fragment.
> 
> ah I see, i checked https://github.com/facebookresearch/hydra/tree/1.0_branch/news before this and didnt see anything under there so I thought 1.0_branch behaves differently. will fix.

nvm, should have checked here https://github.com/facebookresearch/hydra/blob/a8daf4823fb4b155f55fa9ada13394423e8cbfed/website/versioned_docs/version-1.0/development/documentation.md

2021-01-26 23:23 UTC, omry commented
> > Are you planning on releasing hydra 1.0.6 for this?
> > if so, you should include a news fragment.
> 
> ah I see, i checked https://github.com/facebookresearch/hydra/tree/1.0_branch/news before this and didnt see anything under there so I thought 1.0_branch behaves differently. will fix.

Release branch is supposed to be stable, so no news is good news :)

2021-01-27 01:22 UTC, omry approved these changes
Updated comments a bit.
feel free to merge once CI passes.

2021-01-27 02:22 UTC, merged