print out hydra.searchpath value if available
facebookresearch/hydra pull request #1537
Opened 2021-04-06 00:40 UTC by jieru-hu

### hydra.searchpath from primary config
```
$ python /Users/jieru/workspace/hydra-fork/hydra/examples/advanced/config_search_path/my_app.py --info searchpath

Config search path
******************
| Provider                 | Search path                                                                              |
-----------------------------------------------------------------------------------------------------------------------
| hydra                    | pkg://hydra.conf                                                                         |
| main                     | file:///Users/jieru/workspace/hydra-fork/hydra/examples/advanced/config_search_path/conf |
| hydra-colorlog           | pkg://hydra_plugins.hydra_colorlog.conf                                                  |
| hydra-submitit-launcher  | pkg://hydra_plugins.hydra_submitit_launcher.conf                                         |
| hydra.searchpath in main | pkg://additonal_conf                                                                     |
| schema                   | structured://                                                                            |
-----------------------------------------------------------------------------------------------------------------------
```

###  no hydra.searchpath configured
```
(pytest38) jieru-mbp:hydra jieru$ python /Users/jieru/workspace/hydra-fork/hydra/examples/tutorials/basic/running_your_hydra_app/3_working_directory/my_app.py --info searchpath

Config search path
******************
| Provider                | Search path                                                                                                        |
------------------------------------------------------------------------------------------------------------------------------------------------
| hydra                   | pkg://hydra.conf                                                                                                   |
| main                    | file:///Users/jieru/workspace/hydra-fork/hydra/examples/tutorials/basic/running_your_hydra_app/3_working_directory |
| hydra-colorlog          | pkg://hydra_plugins.hydra_colorlog.conf                                                                            |
| hydra-submitit-launcher | pkg://hydra_plugins.hydra_submitit_launcher.conf                                                                   |
| schema                  | structured://                                                                                                      |
------------------------------------------------------------------------------------------------------------------------------------------------
```

###  hydra.searchpath from command line
```
(pytest38) jieru-mbp:hydra jieru$ python /Users/jieru/workspace/hydra-fork/hydra/examples/tutorials/basic/running_your_hydra_app/3_working_directory/my_app.py hydra.searchpath=[file://fake_conf] --info searchpath

Config search path
******************
| Provider                         | Search path                                                                                                        |
---------------------------------------------------------------------------------------------------------------------------------------------------------
| hydra                            | pkg://hydra.conf                                                                                                   |
| main                             | file:///Users/jieru/workspace/hydra-fork/hydra/examples/tutorials/basic/running_your_hydra_app/3_working_directory |
| hydra-colorlog                   | pkg://hydra_plugins.hydra_colorlog.conf                                                                            |
| hydra-submitit-launcher          | pkg://hydra_plugins.hydra_submitit_launcher.conf                                                                   |
| hydra.searchpath in command-line | file://fake_conf                                                                                                   |
| schema                           | structured://                                                                                                      |
---------------------------------------------------------------------------------------------------------------
```

2021-04-06 01:07 UTC, omry requested changes
1. I don't understand why the change here is doing what you are saying it does.
2. Please add tests covering this.

2021-04-06 19:21 UTC, omry commented
> > 1. I don't understand why the change here is doing what you are saying it does.
> 
> I've added a comment there. `hydra.searchpath` is processed [here](https://github.com/facebookresearch/hydra/blob/2930a8d1dd5bc6f2ed3dc5c81d0c4558c7a85ed4/hydra/_internal/config_loader_impl.py#L225), and within the function the repo's config sources is updated to include `hydra.searchpath`, therefore it seems to make sense to load the configuration first.

Can you file a bug for this? loading a config should not change global state.

> > 1. Please add tests covering this.
> 
> done!

2021-04-06 20:06 UTC, jieru-hu commented
> Can you file a bug for this? loading a config should not change global state.

I'm happy to file an issue, but before doing that...

Loading a config here only changes the [caching repo's state](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/config_loader_impl.py#L220-L225), does that count as the global state?

2021-04-06 20:17 UTC, omry commented
the caching repo is instantiated inside load_configuration so it does not count as global state.

2021-04-06 20:19 UTC, jieru-hu commented
> the caching repo is instantiated inside load_configuration so it does not count as global state.

OK, I thought so. No issue is needed then :)

2021-04-07 21:48 UTC, omry requested changes
This will probably break now that I fixed the bug.
rebase take advantage of the hydra.runtime.config_sources?

2021-04-09 16:19 UTC, jieru-hu commented
the failed tests are due to DeprecationWarnings from nevergrad sweeper, I've created a PR here https://github.com/facebookresearch/hydra/pull/1546

2021-04-14 20:57 UTC, omry approved these changes
overall looks good.
See inline nit.

2021-04-14 20:57 UTC, omry commented on hydra/_internal/hydra.py
> +            cfg_type="all",
```suggestion
            cfg_type="hydra",
```

2021-04-14 22:48 UTC, jieru-hu commented
> overall looks good.
> See inline nit.

thanks. fixed!

2021-04-14 22:48 UTC, merged