Allow range(stop) with default start for override grammar
facebookresearch/hydra pull request #1664
Opened 2021-06-10 09:10 UTC by victorjoos

## Motivation

To make the range function more like the default python range(), and easier to type, I added a check if only start was added to set stop to start and start to zero.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

tested by adding a parametrize argument in `test_basic_sweeper.py`.

## Related Issues and PRs

N/A

2021-06-10 12:45 UTC, Jasha10 commented
Thanks for the PR!

It would be good to have a few more tests -- see the `tests/test_overrides_parser.py` file, where most of the `range` tests currently reside.
In particular, I think it would be good to pin down behavior for the following:
- behavior when some inputs are zero or negative, e.g. range(-10, step=1), range(10, step=-1), range(0), ...
  for some of these cases, it is not immediately obvious to me what the behavior should be.
- behavior when called on float inputs

2021-06-10 13:17 UTC, victorjoos commented
Aaah, Thanks for the tips !

I was a bit fast in implementing this, didn't notice I had to also modify the parser. Let me modify the right files.

Not sure about the float inputs, but for the other cases I would say the best is to compare to the default python range implementation: 

 - `range(-10)  == []`
 - `range(-2, step=-1) == [0, -1]`
 - `range(0) == []`
 - `range(10, step=-1) == []`

2021-06-10 13:49 UTC, victorjoos commented
Actually didn't need to change the parser. I added some tests and a new example in the docs.

2021-06-10 17:14 UTC, jieru-hu approved these changes
one nit, otherwise lgtm. Thanks!

2021-06-10 17:14 UTC, jieru-hu commented on news/1664.feature
> +Allow range() in override grammar to have only one argument (the stop value).
pls add a line after this.

2021-06-10 17:14 UTC, jieru-hu commented
@omry  could you take a look as well?

2021-06-10 17:16 UTC, omry commented
Of course. but as I am in the middle of releasing 1.1 this will wait.

2021-06-11 19:22 UTC, omry requested changes
Thanks. Looking pretty good.
See comments.

2021-06-11 19:22 UTC, omry commented on tests/test_basic_sweeper.py
> +        param(["a=range(3)"], None, [[["a=0"], ["a=1"], ["a=2"]]], id="range_no_start"),
This is testing the basic sweeper. remove this test, it's not needed here.

2021-06-11 19:22 UTC, omry commented on tests/test_overrides_parser.py
> +        ),
Add a few tests to test_eval, it also checks the resulting output and not just the parsed object.

2021-06-11 19:22 UTC, omry commented on hydra/_internal/grammar/grammar_functions.py
> +    step: Union[int, float] = 1,
Add a sentence to the function doc describing the new functionality.

2021-06-11 19:22 UTC, omry commented on news/1664.feature
> +Allow range() in override grammar to have only one argument (the stop value).
```suggestion
Allow range() in override grammar to have only one argument (the stop value), e.g. range(3)
```

2021-06-21 10:44 UTC, victorjoos commented
Thank you, sorry for the delay. I implemented your suggestions.

2021-06-21 19:34 UTC, omry approved these changes
Looking good, thanks.

2021-06-21 19:35 UTC, omry commented
We have some existing CI failures we are looking at. Will likely need you to rebase once those are fixed to get CI green again.

2021-06-23 02:02 UTC, jieru-hu commented
@victorjoos  could you rebase master and force push to this branch? Many thanks!

2021-06-23 17:28 UTC, merged