ray remote resources as plain dict
facebookresearch/hydra pull request #1737
Opened 2021-07-28 13:20 UTC by igorgad

## Motivation
 Fix error with custom resources on ray launcher.
`TypeError: The 'resources' keyword argument must be a dictionary, but received type <class 'omegaconf.dictconfig.DictConfig'>.`

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

No, sorry

## Test Plan

Tested locally. This is a very simple mod and shouldn't break anything else.

## Related Issues and PRs

Nope

2021-07-30 16:44 UTC, jieru-hu commented
thank you @igorgad !

1. could you fix the lints? see our [developer guide](https://hydra.cc/docs/development/overview)
2. could you share more info on what triggered this error exactly? (so we  can see if adding some tests would help.)

2021-07-30 16:45 UTC, jieru-hu requested changes
see comment. thanks!

2021-07-30 18:54 UTC, igorgad commented
Hi,
1. Don't know what `black . --check` has been complaining on circleci but here is working as expected.
```
nox > cd plugins/hydra_ray_launcher
nox > black .
nox > isort .
nox > cd /Users/igor/workspace/hydra
nox > mypy --strict plugins/hydra_ray_launcher/hydra_plugins --config-file /Users/igor/workspace/hydra/.mypy.ini
nox > mypy --strict --namespace-packages --config-file /Users/igor/workspace/hydra/.mypy.ini plugins/hydra_ray_launcher/tests
```
2. Using the following override for `hydra/launcher` is enough to reproduce the error
```
_target_: hydra_plugins.hydra_ray_launcher.ray_launcher.RayLauncher
ray:
  init:
    address: null
  remote:
    num_cpus: 1
    resources: {V100: 1}
```
and it's triggered by using the `resources` dict, which for me is very handy for choosing the training GPU.

2021-08-12 20:53 UTC, jieru-hu commented
so sorry for getting back to this late! 

could you try running the `lint` session and see if you repro the failures?
```
nox -s lint
```
Also to make sure we have a clean git history, could you try rebase your branch on top of master and then force push to this PR?
something like the following. 
```
git checkout master && git fetch upstream && git merge  upstream/master
git checkout <branch>
git rebase master
git push --force

```

2021-08-16 18:18 UTC, Jasha10 requested changes
One small remark

2021-08-16 18:18 UTC, Jasha10 commented on plugins/hydra_ray_launcher/hydra_plugins/hydra_ray_launcher/_launcher_util.py
> +        run_job_ray = ray.remote(**OmegaConf.to_container(ray_remote, resolve=True))(
```suggestion
        run_job_ray = ray.remote(**OmegaConf.to_container(ray_remote, resolve=True, throw_on_missing=True))(
```
Using `throw_on_missing=True` would be consistent with the previous behavior.

Particularly, if `ray_remote` is a simple DictConfig with a missing value, e.g. if
```python
ray_remote = OmegaConf.create({"a": 123, "b": "???"})
```
then the previous behavior would be to throw a `MissingMandatoryValue` error when the `**` operator is invoked as `**ray_remote`.

2021-08-16 18:56 UTC, Jasha10 commented
Sorry it looks like my suggestion caused a lint failure.

2021-08-16 20:12 UTC, Jasha10 commented
> This pull request **introduces 1 alert** when merging [f297d51](https://github.com/facebookresearch/hydra/commit/f297d51e26f2820ce672c0562565ae9f73ba2057) into [2a6cbfa](https://github.com/facebookresearch/hydra/commit/2a6cbfaa04c0a5569619d9a01e4dbd6f2e17b1b1) - [view on LGTM.com](https://lgtm.com/projects/g/facebookresearch/hydra/rev/pr-266290255a0db9a9be4d5ae175363c3c05393bdc)
> 
> **new alerts:**
> 
>     * 1 for Wrong name for an argument in a call

This LGTM.com issue is happening because the `throw_on_missing` argument to `OmegaConf.to_container` is not supported in OmegaConf 2.1.0. (It is available on the OmegaConf master branch, and will be part of the OmegaConf 2.1.1 release).

I think it will be best to not use `throw_on_missing` after all...

2021-08-17 16:13 UTC, Jasha10 commented
I've pushed another commit reverting use of the `throw_on_missing` keyword. Sorry for the confusion.

2021-08-18 20:28 UTC, jieru-hu commented
Thank you @Jasha10 @igorgad 

@igorgad  thanks for fixing the lints. it looks like the CI is still failing with issues that have been fixed on master. Could you rebase and force push? Many thanks. Other than that, the pr lgtm.

2021-08-24 17:20 UTC, merged