Update config.py
facebookresearch/hydra pull request #1920
Opened 2021-12-09 11:00 UTC by Anirudh257

Add account parameter of slurm

## Motivation

The slurm cluster used by me needs me to specify the **account** parameter in the bash script. It wasn't present in this current version.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

No need for tests. I added it as an optional parameter

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)
[1664](https://github.com/facebookincubator/submitit/pull/1664) is related to this.

2021-12-09 18:54 UTC, Jasha10 commented
Thanks @Anirudh257.
FYI I've pushed a commit to this PR branch because the CI was failing (see the red "x" next to the first commit).

2021-12-09 18:56 UTC, jieru-hu commented
thanks, pls update the document and a news segment as well
https://hydra.cc/docs/development/overview/

here is an example PR.

2021-12-09 18:56 UTC, jieru-hu requested changes
see comment. thanks!

2021-12-09 20:50 UTC, Anirudh257 commented
Thanks, @Jasha10 and @jieru-hu I wasn't able to figure out how to correct the first failing CI.

2022-01-11 07:16 UTC, Jasha10 commented
@Anirudh257, have you tested that this implementation is working with submitit?

2022-01-11 14:49 UTC, Anirudh257 commented
@Jasha10 , yes it works on my system.

2022-01-11 18:00 UTC, Jasha10 commented
Great, thanks!

2022-01-14 18:07 UTC, jieru-hu commented
rebase the  PR on main.

2022-01-17 19:24 UTC, Jasha10 approved these changes

2022-02-08 00:55 UTC, merged

2022-04-16 18:27 UTC, RemyLau commented
Hi, would it be possible to release this patch? The account setting is quite crucial and it would be great if this patch is released on PyPI!

2022-04-16 20:25 UTC, pixelb commented
We're releasing 1.2 to pypi within a couple of weeks