Add _resolve_ flag to instantiate.
facebookresearch/hydra pull request #2269
Opened 2022-06-20 11:28 UTC by kpoeppel

## Motivation

See issue #2268. Passing the whole configuration (e.g. via eval) to an instantiated object is impossible as the resolution breaks due to different top-level of the configuration.
With this addition, special objects are not resolved a second time (of course one resolve has to be called beforehand).

### Have you read the [Contributing Guidelines on pull  #requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

A simple test was already added. The default behaviour doesn't change.

## Related Issues and PRs

Issue #2268

2022-07-02 02:12 UTC, Jasha10 requested changes
This PR does not address the use-case outlined in [this comment](https://github.com/facebookresearch/hydra/issues/2268#issuecomment-1161343049). The assertion in the following script should pass:
```python
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf


def train(cfg: DictConfig, num: int):
    return num


cfg = OmegaConf.create(
    """
func:
    _target_: __main__.train
    num: 123
"""
)
x = instantiate(cfg.func, cfg=cfg, _resolve_=False)
assert x == 124
```
The script instead fails with a `TypeError`.

2022-11-06 12:04 UTC, Jasha10 commented on hydra/_internal/instantiate/_instantiate2.py
> +                or node.get("_resolve_", True))
I too should apologize for my late response.

> The problem is how to tackle recursion here, as things become self-referential potentially (-> infinite recursion).

I am confused. Could you give me an example where infinite recursion would come up?

2022-11-06 12:33 UTC, Jasha10 commented
I've just realized that this PR is quite similar to what is discussed in issue #1758, specifically Omry's suggestion from [this comment](https://github.com/facebookresearch/hydra/issues/1758#issuecomment-897092551).

2022-11-06 14:53 UTC, kpoeppel commented
Do you think this can be merged now from a software architecture point of view?
I still need to fix the failing tests, maybe also need some help  because of their generic nested structure.

2022-11-06 16:57 UTC, Jasha10 commented
> Do you think this can be merged now from a software architecture point of view?

Not sure. We might need to move the `OmegaConf.resolve` calls from the `instantiate` function into a more deeply nested function (such as `instantiate_node`).

This PR needs more tests before it can be merged (there's only one test for `_resolve_` currently).

2026-06-19 06:45 UTC, omry commented
Thanks for the PR and the discussion around this.

I agree that the general capability is desirable, but this needs careful design and re-evaluation before implementation. The eager `OmegaConf.resolve(config)` in `instantiate()` was added intentionally in #1487 to fix serialization/pickling problems reported in #1483 and #1295. In short, Hydra resolves while the config tree is still intact, then detaches OmegaConf containers before passing them into the target so they do not carry an unpicklable parent/sibling graph into user objects.

A simple `_resolve_: false` flag risks reopening that class of bug unless the design is clear about unresolved containers, parent links, relative interpolations, and serialization safety.

I opened #3216 to evaluate this as a future instantiate API change. I am closing this PR because it is stale and not complete enough for the current codebase, but I would welcome a future attempt in the context of #3216, with the explicit requirement that the serialization safety from #1487 is retained.

2026-06-19 06:45 UTC, closed without merging