Upgrade Optuna from v2.x.x to v3.0.0
facebookresearch/hydra pull request #2360
Opened 2022-08-29 08:23 UTC by keisuke-umezawa

## Motivation

(Write your motivation for proposed changes here.)
To upgrade Optuna from v2.x.x to v3.0.0

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebookresearch/hydra/blob/master/CONTRIBUTING.md)?

Yes

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

By the existing unit tests

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)
Fixes https://github.com/facebookresearch/hydra/issues/2162

2022-08-29 08:45 UTC, keisuke-umezawa commented
Seems that the lint fails even for the main https://app.circleci.com/pipelines/github/facebookresearch/hydra/14763/workflows/e495a59a-f45c-4531-a51a-898dad566d50/jobs/146566

2022-09-06 16:40 UTC, Jasha10 requested changes
Thanks @keisuke-umezawa!
Do you expect that this change to the optuna sweeper plugin will be backwards compatible for Hydra users?
Could you please bump the version in `hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/__init__.py` to `"1.3.0.dev0"`?

2022-09-06 16:40 UTC, Jasha10 commented on plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py
> +            return FloatDistribution(value.start, value.end, log=True)
```suggestion
                return IntDistribution(int(value.start), int(value.end), log=True)
            return FloatDistribution(value.start, value.end, log=True)
```

2022-09-19 07:24 UTC, keisuke-umezawa commented
@Jasha10 

Thank you for your comment!

> Do you expect that this change to the optuna sweeper plugin will be backwards compatible for Hydra users?

If the meaning of the backwards compatibility here is that we can run hydra with both Optuna v2.x and v3.x, we should not merge this PR. This code change can run only with Optuna v3.x.

As Optuna will keep the backwards compatibility for a while, e.g. until v4, we do not need to merge this PR at the moment. But, in that case, one note is that someone needs to merge this PR when Optuna will totally break the backwards compatibility.

2022-09-20 14:49 UTC, Jasha10 commented
> > Do you expect that this change to the optuna sweeper plugin will be backwards compatible for Hydra users?
> 
> If the meaning of the backwards compatibility here is that we can run hydra with both Optuna v2.x and v3.x ...

My question is about the Optuna Sweeper's user API: will Hydra users need to update their yaml configs?
I think the answer is no; users will not need to update anything.

> This code change can run only with Optuna v3.x.

This is fine :)
If users need Optuna v2.x, they can use an old version of the optuna sweeper plugin.

2022-09-20 14:49 UTC, Jasha10 commented
I will push some commits to this PR branch to try and make the CI pass.

2022-10-02 06:07 UTC, keisuke-umezawa commented
> > > Do you expect that this change to the optuna sweeper plugin will be backwards compatible for Hydra users?
> > 
> > If the meaning of the backwards compatibility here is that we can run hydra with both Optuna v2.x and v3.x ...
> 
> My question is about the Optuna Sweeper's user API: will Hydra users need to update their yaml configs?
> I think the answer is no; users will not need to update anything.

Your understanding is correct. They do not need to change it.

> > This code change can run only with Optuna v3.x.
> 
> This is fine :)
> If users need Optuna v2.x, they can use an old version of the optuna sweeper plugin.
> Edit: We are looking into usage patterns to see whether Optuna v3.x is as popular as v2.x. If not, we might delay merging this PR for a while...

Thank you! You can merge it when it is appropriate.

2023-03-09 15:51 UTC, AlexLup commented
It is possibile to install using pip a dev version of hydra sweeper with support for optuna 3 ?

2023-03-18 01:53 UTC, classner commented
Could this please be merged? The 2.1 version of Optuna is very much out-of-date.

2023-04-11 06:16 UTC, AntonClaesson commented
I'd also like this to be merged!

2023-05-29 09:22 UTC, keisuke-umezawa commented
@Jasha10 
Long time no see and thank you for working on it!
Should I do anything to merge this PR to fix CI?

2023-06-01 22:27 UTC, Jasha10 commented
Hi @keisuke-umezawa,

Since it's been a while, it would be good to rebase this diff on top of the `main` branch.

Currently I'm no longer an official maintainer of Hydra. That being said, I do hope this diff can be merged at some point.

2023-06-01 22:32 UTC, Jasha10 commented
@AlexLup 

> It is possibile to install using pip a dev version of hydra sweeper with support for optuna 3 ?


You can pip-install the version of `hydra-colorlog` from this PR
```
pip install 'git+https://github.com/keisuke-umezawa/hydra/@feature/fix-optuna-v3#egg=hydra-optuna-sweeper&subdirectory=plugins/hydra_optuna_sweeper'
```

Or you can git-clone the repo, check out @keisuke-umezawa's `feature/fix-optuna-v3` branch, and run `pip install --editable .` in the `plugins/hydra_optuna_sweeper` subdirectory of the repo.

2023-07-01 22:17 UTC, Jasha10 commented
No problem @keisuke-umezawa. I believe that @omry and @shagunsodhani are current maintainers of Hydra.

I believe the CI failures here are unrelated to this diff. Once #2692 and #2693 are fixed, it should be possible to get the CI green.

2023-07-24 07:06 UTC, tmachnitzki commented
Are there any updates on this? It seems the issues mentioned by @Jasha10 are all merged. I would love to use optuna >= 3 .

2023-07-24 11:37 UTC, odelalleau commented
> Are there any updates on this? It seems the issues mentioned by @Jasha10 are all merged. I would love to use optuna >= 3 .

In the meantime you should be able to install a version with the fix with:
```
pip install git+https://github.com/facebookresearch/hydra.git@93f7ac617c34201b602afd6a838ae07658d62888
```
(this is latest current commit, but feel free to pick whatever commit works best for you)

2024-07-20 03:10 UTC, Zhylkaaa commented
I would like to bump this PR :) 
Lack of optuna>=3 starts to become problematic since introduction of new `pandas` version, I need to have 2 separate envs to extract my data (with pandas) and one for actuall sweeps with olred version of SQLAlchemy (optuna<3 relies on older SQLAlchemy incompatible with new pandas)

Can I help with any requested changes?

2025-10-09 08:34 UTC, breznak commented
ping after 1 year, @omry any chance to get this merged upstream, please?

2025-10-10 03:09 UTC, nefario7 commented
Sorry for spamming, but @omry if you take a look at this and help get this merged, that will be really helpful!

2025-10-10 16:34 UTC, Zhylkaaa commented
meanwhile there is another PR to bump the version to 4 xD 
https://github.com/facebookresearch/hydra/pull/3046

2026-05-16 02:12 UTC, omry commented
Closing as superseded by newer Optuna upgrade work, including #3046. This 2022 branch is too stale to use as the basis for the current Optuna plugin update.

2026-05-16 02:12 UTC, closed without merging